# Generated by Django 3.2.7 on 2021-09-21 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210921_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='product',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.manufacturer'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='type',
            name='thrust',
            field=models.CharField(max_length=30),
        ),
    ]
