# Generated by Django 3.2.7 on 2021-09-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210921_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
